FROM python:3


WORKDIR /code


COPY requirements.txt /code/requirements.txt


COPY logging.conf /code/logging.conf


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


RUN echo "pip install complete"


COPY ./ClassicalLanguageLearner/db/* /code


CMD ["python", "main.py"]